##  -*-  coding: utf-8; mode: ruby -*-  ##
##  vi: set ft=ruby

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |v|
    v.name   = "vagrant-box-ubuntu-gui"
    v.memory = "1024"

    v.customize [
      "modifyvm",           :id,
      "--vram",             "256",
      "--clipboard",        "bidirectional",
      "--draganddrop",      "bidirectional",
      "--accelerate3d",     "on",
      "--hwvirtex",         "on",
      "--nestedpaging",     "on",
      "--largepages",       "on",
      "--ioapic",           "on",
      "--pae",              "on",
      "--paravirtprovider", "kvm",
    ]
  end

  config.vm.provision("root", type: "shell",
                      path: "provision.root.sh",
                      privileged: true)
  config.vm.synced_folder(".", "/vagrant", disabled: true)

end
